# Generated by Django 3.1.4 on 2021-10-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esr21_follow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='call_status',
            field=models.CharField(choices=[('successful', 'Successful'), ('unsuccessful', 'Unsuccessful')], default='successful', max_length=50),
        ),
        migrations.AddField(
            model_name='logentry',
            name='reason_unsuccesful',
            field=models.CharField(blank=True, choices=[('no_response', 'Phone rang, no response but voicemail left'), ('no_response_vm_not_left', 'Phone rang no response and no option to leave voicemail'), ('disconnected', 'Phone did not ring/number disconnected'), ('number_changed', 'No longer the phone number of BHP participant'), ('N/A', 'Not Applicable')], max_length=150, null=True, verbose_name='Reasons call unsuccessful?'),
        ),
    ]
