# Generated by Django 3.1.4 on 2021-10-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esr21_follow', '0002_auto_20211001_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklist',
            name='visit_code',
            field=models.CharField(editable=False, max_length=25, null=True),
        ),
    ]
