# Generated by Django 3.1.4 on 2021-10-06 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esr21_follow', '0003_worklist_visit_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='worklist',
            unique_together={('subject_identifier', 'visit_code')},
        ),
    ]
