# Generated by Django 3.1.4 on 2021-10-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esr21_follow', '0003_worklist_appointment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
    ]
