# Generated by Django 3.1.4 on 2021-10-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esr21_follow', '0004_logentry_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklist',
            name='appointment_id',
        ),
        migrations.AddField(
            model_name='worklist',
            name='appt_status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('incomplete', 'Incomplete'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_index=True, default='new', help_text="If the visit has already begun, only 'in progress' or 'incomplete' are valid options", max_length=25, verbose_name='Status'),
        ),
    ]
