# Generated by Django 3.1.4 on 2021-10-07 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esr21_follow', '0005_call_log_logentry_reasonsunwilling'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='call',
            unique_together={('subject_identifier', 'visit_code')},
        ),
    ]
