# Generated by Django 3.1.4 on 2021-10-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esr21_follow', '0006_auto_20211007_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklist',
            name='appt_datetime',
            field=models.DateTimeField(db_index=True, default=None, verbose_name='Appointment date and time'),
            preserve_default=False,
        ),
    ]
